dist: xenial
language: node_js
node_js:
  - 16.14.0
services:
  - mysql
install:
  - cd server && npm install
  - npm install codacy-coverage --save
  - npm install mocha-lcov-reporter --save
  - npm install --save-dev nyc
script:
  - npm run test
  - mkdir .nyc_output
  - npx nyc report --reporter=lcov

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/*.lcov

branches:
  only:
    - main
    - develop
    - Travis-config

