dist: xenial
language: node_js
node_js:
  - 16.14.0
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p123123
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE tfgdb_test;'
install:
  - cd server && npm install
script:
  - npm run test
branches:
  only:
    - main
    - develop
    - Travis-config

