dist: xenial
language: node_js
node_js:
  - 16.14.0
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tfgdb_test;'
install:
  - cd server && npm install
script:
  - npm run test
branches:
  only:
    - main
    - develop
    - Travis-config

