dist: xenial
language: node_js
node_js:
  - 16.14.0
services:
  - mysql
install:
  - cd server && npm install
  - npm install --save-dev nyc
script:
  - npm run test
branches:
  only:
    - main
    - develop
    - Travis-config

